# Generated by Django 6.0.1 on 2026-01-16 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consorzio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Consorzi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('indirizzo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Persone',
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('inizio_astratto', models.DateTimeField(help_text="Inserisci giorno e ora. L'anno verrà ignorato (sarà salvato come 2000).")),
                ('consorzio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rami', to='core.consorzio')),
            ],
            options={
                'verbose_name_plural': 'Rami',
                'ordering': ['consorzio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Giro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.IntegerField()),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giri', to='core.ramo')),
            ],
            options={
                'verbose_name_plural': 'Giri',
                'ordering': ['ramo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durata', models.DurationField()),
                ('ordine', models.IntegerField()),
                ('giro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turni', to='core.giro')),
                ('proprietari', models.ManyToManyField(related_name='turni_proprietario', to='core.persona')),
                ('utilizzatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turni_utilizzatore', to='core.persona')),
            ],
            options={
                'verbose_name_plural': 'Turni',
                'ordering': ['giro', 'ordine'],
                'unique_together': {('giro', 'ordine')},
            },
        ),
    ]
