# Generated by Django 6.0.1 on 2026-01-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnoproprietario',
            old_name='tempo_allocato',
            new_name='tempo',
        ),
    ]
