# Generated by Django 6.0.1 on 2026-01-16 23:31

import core.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tempo_allocato_turnoproprietario_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='durata',
            field=core.fields.DurationHHMMField(default=datetime.timedelta(0), editable=False),
        ),
        migrations.AlterField(
            model_name='turnoproprietario',
            name='tempo',
            field=core.fields.DurationHHMMField(help_text='Tempo allocato a questo proprietario (hh:mm)'),
        ),
    ]
